/**
 * Per-template prompt fragment for atlas-bun-cli (Bun 1.2+ runtime +
 * Commander 12.x + ink 5.x + chalk 5 + zod + bun:test). Plan T.2.5.
 *
 * The sandbox is a CLI, not a web app. The port-3001 surface is a tiny
 * Bun.serve status page; the developer's primary deliverable is subcommand
 * files under src/commands/ that the user invokes via the E2B Exec API.
 * (Port 3001, not 3000 — the e2bdev base image already binds :3000.)
 */
export const BUN_CLI_PROMPT = [
  "## Target sandbox",
  "",
  "Your diff will be applied to a Bun 1.2+ CLI project running in an E2B sandbox (template: atlas-bun-cli).",
  "",
  "- The CLI entrypoint is **`src/cli.ts`** — declares the Commander root program and registers subcommands. Keep it thin: import + register, no business logic.",
  "- Add new subcommands to **`src/commands/<name>.tsx`** — one file per subcommand. Each file default-exports the ink component (the screen) and named-exports `register<Name>(program: Command): void`.",
  "- Add reusable helpers to **`src/lib/<helper>.ts`** — pure functions, no Commander references, easy to unit-test.",
  "- Add tests in **`tests/<feature>.test.ts`** using `bun:test` (`import { describe, it, expect } from \"bun:test\"`).",
  "- A status-page HTTP server (`src/server.ts`) runs on port 3001 so the canvas iframe has something to render. **Do NOT remove or repurpose it** — the sandbox preview iframe depends on it. (Port 3001, not 3000 — the e2bdev base image already binds :3000.)",
  "",
  "## What's installed (use these — don't reinvent)",
  "",
  "- **bun** 1.2+ — runtime, package manager, test runner, bundler. Runs `.ts`/`.tsx` natively.",
  "- **commander** 12.x — argv parsing. Pattern: `program.command(\"name\").description(\"...\").option(\"-x, --xxx <v>\", \"...\", \"default\").action((opts) => {...})`.",
  "- **ink** 5.x — React for terminal UIs. Use `<Box flexDirection=\"column\">`, `<Text color=\"green\">`, `<Newline>`. Drive output with `render(<Component />)` from inside the action handler.",
  "- **ink-spinner** — `<Spinner type=\"dots\" />` for in-flight indicators.",
  "- **ink-text-input** — interactive text prompts.",
  "- **ink-select-input** — interactive list pickers.",
  "- **chalk** 5 — color primitives for non-ink code paths (early-exit error printing, plain piped output). Reach for chalk when you're outside an ink `<Text>` tree.",
  "- **zod** 3.x — runtime input validation. Use for parsing config files, JSON inputs, env vars.",
  "- **react** 18 — peer of ink (use hooks: `useState`, `useEffect`).",
  "",
  "## How Atlas exercises the CLI",
  "",
  "The CLI is exercised by Atlas via E2B's **Exec API** — NOT via the iframe. The iframe shows a status page only. Atlas runs:",
  "",
  "```ts",
  "await sandbox.commands.run(\"bun run src/cli.ts <subcommand> [args]\");",
  "```",
  "",
  "Design subcommands to be clean stdout/stderr producers; do NOT write user-facing UI to port 3001.",
  "",
  "## Conventions + style",
  "",
  "- Subcommand files are `.tsx`; pure-helper files are `.ts`.",
  "- Use `Bun.file(path)` / `Bun.write(path, data)` for IO — NOT `node:fs/promises`. Bun's APIs are simpler, faster, and the prompt explicitly endorses them.",
  "- Use `Bun.serve(...)` for any HTTP server work — NOT `http`/`express`.",
  "- Use `import.meta.main` to gate \"run as binary\" code so tests can import the module without triggering side effects.",
  "- Top-of-file `#!/usr/bin/env bun` shebang is OK on `src/cli.ts`. Do NOT add it to subcommand files.",
  "- Do NOT assume Node-specific globals (`__dirname`, `__filename`, `require`). Bun is ESM-only by default; use `import.meta.url` and `import.meta.dir` instead.",
  "- Do NOT add new dependencies via package.json patches unless the user explicitly asks. Adding deps means rebuilding the template.",
  "- Do NOT write a top-level web app — this is a CLI sandbox. The status page is the only HTTP surface; do not turn it into a real UI.",
  "",
  "## Subcommand pattern (canonical)",
  "",
  "```tsx",
  "// src/commands/greet.tsx",
  "import { Command } from \"commander\";",
  "import React from \"react\";",
  "import { render, Box, Text } from \"ink\";",
  "",
  "export default function Greet({ name }: { name: string }) {",
  "  return (",
  "    <Box flexDirection=\"column\">",
  "      <Text color=\"green\">Hello, {name}!</Text>",
  "    </Box>",
  "  );",
  "}",
  "",
  "export function registerGreet(program: Command): void {",
  "  program",
  "    .command(\"greet\")",
  "    .description(\"Greet someone\")",
  "    .option(\"-n, --name <name>\", \"name to greet\", \"world\")",
  "    .action((opts: { name: string }) => render(<Greet name={opts.name} />));",
  "}",
  "```",
  "",
  "Then in `src/cli.ts`:",
  "",
  "```ts",
  "import { registerGreet } from \"./commands/greet.js\";",
  "// ... inside buildProgram():",
  "registerGreet(program);",
  "```",
  "",
  "## Diff format (CRITICAL)",
  "",
  "Same as the other templates: emit ONE unified diff with multiple file hunks. For every file you intend to fully own, emit it as a **brand-new file from `/dev/null`** even if the file already exists in the sandbox:",
  "",
  "```",
  "diff --git a/src/commands/greet.tsx b/src/commands/greet.tsx",
  "new file mode 100644",
  "--- /dev/null",
  "+++ b/src/commands/greet.tsx",
  "@@ -0,0 +1,N @@",
  "+<full file contents, line by line>",
  "```",
  "",
  "The hunk header `@@ -0,0 +1,N @@` MUST declare the exact count of `+` lines.",
  ""
].join("\n");
