/**
 * Per-template prompt fragment for atlas-dlt-python (Python 3.12 + dlt 1.4+ +
 * DuckDB 1.x + dbt-core 1.9+ + dbt-duckdb 1.9+ + pandas 2.x + pyarrow + a
 * tiny FastAPI status app for the E2B preview iframe). Plan T.2.4.
 */
export const DLT_PYTHON_PROMPT = [
  "## Target sandbox",
  "",
  "Your diff will be applied to a live Python 3.12 + dlt + DuckDB + dbt-core data-pipeline project running in an E2B sandbox (template: atlas-dlt-python).",
  "",
  "**This is a data pipeline. It has no UI.** A tiny FastAPI status app at `app/main.py` runs on port 3000 ONLY so the preview iframe shows pipeline status (`/health`, `/runs`, `/pipelines`). You typically do **NOT** modify `app/main.py` — only edit it if the user explicitly asks for a custom status endpoint.",
  "",
  "Your changes go into:",
  "- **`pipelines/<pipeline_name>.py`** — extract + load. Use `@dlt.resource`, `@dlt.source`, `dlt.pipeline(...).run(...)`. The destination is DuckDB at `/code/data/atlas.duckdb` by default.",
  "- **`dbt_project/models/<model_name>.sql`** — transformations. Use `{{ source(...) }}` to read dlt-loaded tables, `{{ ref(...) }}` to chain models. Add column descriptions + tests in `dbt_project/models/sources.yml`.",
  "- **`tests/test_<feature>.py`** — pytest tests for new pipelines.",
  "",
  "Do **NOT** write a top-level `index.html` or React components or any frontend — there's no Next dev server in this template. The preview iframe shows the FastAPI status app's `/runs` + `/pipelines` endpoints.",
  "",
  "## What's installed (use these — don't reinvent)",
  "",
  "### Pipeline (E + L of ELT)",
  "- **dlt 1.4+** with the `[duckdb]` extra — `import dlt`. Resources via `@dlt.resource`, sources via `@dlt.source`, pipelines via `dlt.pipeline(pipeline_name=..., destination=dlt.destinations.duckdb(path), dataset_name=...)`.",
  "- **duckdb 1.1+** — embedded warehouse. The single `/code/data/atlas.duckdb` file is the entire data store. Read-only queries via `duckdb.connect(path, read_only=True)`.",
  "- **pandas 2.2+** + **pyarrow 18+** — for in-memory transforms inside resources / ad-hoc analysis. dlt also uses pyarrow internally for schema inference.",
  "",
  "### Transforms (T of ELT)",
  "- **dbt-core 1.9+** + **dbt-duckdb 1.9+** — `cd dbt_project && uv run dbt run --profiles-dir .` (the profile is co-located, NOT in `$HOME/.dbt/`).",
  "- Use `{{ source('raw', 'tablename') }}` to read dlt-loaded tables. Declare every source in `dbt_project/models/sources.yml` first — dbt errors on undeclared sources.",
  "- Use `{{ ref('upstream_model') }}` to depend on another dbt model.",
  "- Use `{{ config(materialized='view'|'table'|'incremental') }}` at the top of each model. Default in `dbt_project.yml` is `view`.",
  "",
  "### Status surface (DON'T modify unless asked)",
  "- **fastapi 0.115+** + **uvicorn[standard]** — serves `/` (metadata), `/health` (liveness), `/runs` (last N pipeline runs from `_dlt_loads`), `/pipelines` (modules under `pipelines/`), `/docs` (Swagger UI).",
  "- **pydantic 2.x** — typed schemas if you DO need to extend the status app.",
  "",
  "### Test + lint",
  "- **pytest** + **pytest-asyncio** — `uv run pytest -v`. Tests live in `tests/`.",
  "- **ruff** — line-length 100, py312, `dbt_project/dbt_packages` + `dbt_project/target` excluded.",
  "",
  "## Style + conventions",
  "",
  "### dlt resources",
  "- Use `@dlt.resource(write_disposition='append'|'replace'|'merge')` — `replace` is safest for v1.",
  "- Yield dicts (or Pydantic models, or pandas DataFrames). dlt infers the schema.",
  "- For HTTP sources, use `httpx` — yield from response JSON inside the resource body.",
  "- For SQL sources, prefer dlt's shipped `sql_database` source helper — don't hand-roll SELECTs.",
  "- Keep one resource per file under `pipelines/`. Compose into a `@dlt.source` only if grouping is meaningful.",
  "- Use `pandas` + `pyarrow` for in-memory transforms before yielding (e.g. type coercion, column renames).",
  "",
  "### dbt models",
  "- Materialization: `view` for cheap chains, `table` for terminal aggregations, `incremental` only when you understand the unique key.",
  "- Always declare sources in `sources.yml` BEFORE referencing them with `{{ source(...) }}`.",
  "- Add `tests:` blocks (unique, not_null, accepted_values) on primary keys + foreign-key-shaped columns.",
  "- Use Jinja sparingly — readability > cleverness.",
  "",
  "### File ownership",
  "- Do NOT modify `app/main.py` (the FastAPI status app) unless the user explicitly asks for a custom status endpoint.",
  "- Do NOT modify `pyproject.toml` to add deps unless the user explicitly asks. Adding deps means rebuilding the template.",
  "- Do NOT modify `dbt_project/dbt_project.yml` or `dbt_project/profiles.yml` unless changing the warehouse target.",
  "",
  "### Type hints + docstrings",
  "- Type hints on every function signature (PEP 695 fine).",
  "- Use Pydantic v2 idioms when typing pipeline configs: `model_config = ConfigDict(...)`, `field_validator`, `model_dump()` (not `.dict()`).",
  "",
  "## Diff format (CRITICAL)",
  "",
  "Same as other Python templates: emit ONE unified diff with multiple file hunks. For every file you intend to fully own, emit it as a **brand-new file from `/dev/null`**:",
  "",
  "```",
  "diff --git a/pipelines/users.py b/pipelines/users.py",
  "new file mode 100644",
  "--- /dev/null",
  "+++ b/pipelines/users.py",
  "@@ -0,0 +1,N @@",
  "+<full file contents>",
  "```",
  "",
  "The hunk header `@@ -0,0 +1,N @@` MUST declare the exact count of `+` lines. Off-by-one truncates the file at the sandbox.",
  "",
  "For dbt models, write `.sql` files under `dbt_project/models/` and add the matching `sources.yml` source/model entries:",
  "",
  "```",
  "diff --git a/dbt_project/models/users_summary.sql b/dbt_project/models/users_summary.sql",
  "new file mode 100644",
  "--- /dev/null",
  "+++ b/dbt_project/models/users_summary.sql",
  "@@ -0,0 +1,N @@",
  "+<full SQL contents>",
  "```",
  ""
].join("\n");
