/**
 * Per-template prompt fragment for atlas-expo-rn (Expo SDK 52 + React Native
 * 0.76+ + expo-router 4.x + NativeWind 4.x + TypeScript 5.6 strict). Plan
 * T.2.3.
 *
 * IMPORTANT: this template's sandbox runs the WEB build (`expo start --web
 * --port 3000`) so the iframe can render react-native-web output. Native iOS
 * / Android simulator preview is NOT available in v1.
 */
export const EXPO_RN_PROMPT = [
  "## Target sandbox",
  "",
  "Your diff will be applied to a live Expo SDK 52 + React Native 0.76+ + expo-router 4 + NativeWind 4 + TypeScript 5.6 strict project running in an E2B sandbox (template: atlas-expo-rn). The sandbox renders the **WEB build** (react-native-web) on port 3000 — iOS/Android simulator preview is NOT available; design for both web AND native, but assume the user only sees the web rendering during the ritual.",
  "",
  "- The dev-server entry is **`app/_layout.tsx`** (Expo Router root) + **`app/index.tsx`** (the URL `/` route).",
  "- Routing is **file-based** via expo-router 4 — same mental model as Next.js App Router but for RN. `app/foo.tsx` → `/foo`. `app/(group)/bar.tsx` → `/bar` (group folders don't appear in URL). `app/[id].tsx` → dynamic segment. `app/<dir>/_layout.tsx` → layout for that dir.",
  "- The template ships an `app/(tabs)/_layout.tsx` example (tabs container) + `app/(tabs)/index.tsx` (first tab). Extend this pattern for tabbed apps — group-folder convention `app/(tabs)/<route>.tsx` keeps the URL clean while letting the layout add the tab bar.",
  "- New screens go in `app/`. Shared components go in `components/` (you may create this directory). Utilities go in `lib/` (you may create this directory).",
  "- Do **NOT** write a top-level `index.html` or `pages/` directory. Expo Router uses `app/` only.",
  "- Do **NOT** import from `next/*`, `next-auth`, or any Next-specific module. This is a React Native project.",
  "",
  "## What's installed (use these — don't reinvent)",
  "",
  "- **expo** ^52, **expo-router** ^4 — SDK + file-based routing",
  "- **@expo/metro-runtime** ^4 — web runtime support",
  "- **react** ^18.3, **react-dom** ^18.3, **react-native** ^0.76",
  "- **react-native-web** ^0.19 — bridges RN components to DOM for the web build",
  "- **nativewind** ^4 — Tailwind utility classes on RN components via the babel plugin",
  "- **TypeScript** ^5.6 strict — every export typed; no implicit any",
  "- **jest** + **jest-expo** — test framework (`pnpm test`)",
  "",
  "## RN component idioms (NOT DOM)",
  "",
  "Use React Native primitives, not HTML tags:",
  "",
  "- `<View>` instead of `<div>` — flex container; default flexDirection='column' (NOT 'row' like CSS)",
  "- `<Text>` instead of `<span>`/`<p>` — ALL text must be wrapped in `<Text>`. Bare strings inside `<View>` throw a runtime error.",
  "- `<Pressable>` (or `<TouchableOpacity>`) instead of `<button>` — for taps",
  "- `<TextInput>` instead of `<input>` — for text entry",
  "- `<ScrollView>` or `<FlatList>` instead of relying on CSS `overflow: scroll`",
  "- `<Image source={{ uri }}>` instead of `<img src>` — note the `source` prop, not `src`",
  "",
  "## NativeWind className syntax",
  "",
  "Tailwind utility classes work on every RN component via the `className` prop:",
  "",
  "```tsx",
  "import { Text, View } from \"react-native\";",
  "",
  "export default function Screen() {",
  "  return (",
  "    <View className=\"flex-1 items-center justify-center bg-white p-6\">",
  "      <Text className=\"text-3xl font-bold text-atlas-primary\">Hello</Text>",
  "    </View>",
  "  );",
  "}",
  "```",
  "",
  "Notes:",
  "- Most Tailwind classes work as-is (`flex-1`, `items-center`, `bg-white`, `text-3xl`, `font-bold`, `p-6`, `mt-2`, `rounded-lg`, etc.).",
  "- Some web-only classes are no-ops (`cursor-pointer`, `hover:*`, `focus-visible:*`) — RN doesn't have hover; use `:active` via `<Pressable>`'s style callback instead.",
  "- The template's `tailwind.config.js` defines `atlas-primary`, `atlas-background`, `atlas-muted`, `atlas-accent` colors. Use them.",
  "- DO NOT reach for inline `style={{ }}` color overrides — use the className tokens.",
  "",
  "## Routing — expo-router not next/link, not HTML anchor",
  "",
  "Use the `Link` component from `expo-router`:",
  "",
  "```tsx",
  "import { Link } from \"expo-router\";",
  "// internal navigation",
  "<Link href=\"/(tabs)\">Home</Link>",
  "<Link href=\"/profile/123\">Profile</Link>",
  "```",
  "",
  "Do NOT import `Link` from `next/link` — that module isn't installed. Do NOT use raw HTML `<a href>` tags — they don't render on native.",
  "",
  "For programmatic navigation use the `router` import:",
  "",
  "```tsx",
  "import { router } from \"expo-router\";",
  "router.push(\"/(tabs)\");",
  "router.back();",
  "```",
  "",
  "## File-based routing convention recap",
  "",
  "- `app/index.tsx` → URL `/`",
  "- `app/foo.tsx` → URL `/foo`",
  "- `app/foo/_layout.tsx` → wraps every route under `app/foo/`",
  "- `app/(group)/route.tsx` → URL `/route` (group folders are organizational only, never appear in URL)",
  "- `app/[id].tsx` → dynamic segment, accessible via `useLocalSearchParams()`",
  "- `app/+not-found.tsx` → 404 fallback",
  "",
  "## What you CANNOT assume",
  "",
  "- **No `document`, no `window`, no `localStorage`.** These exist on web but throw on native. If you need persistence, use `expo-secure-store` (NOT installed by default — would require a template rebuild) or read/write a backend (separate sandbox).",
  "- **No CSS files / `<style>` tags.** All styling goes through NativeWind className OR `StyleSheet.create({})` from `react-native`.",
  "- **No `<head>` / `<meta>` / `<title>` injection.** Use `Stack.Screen options={{ title: 'X' }}` from expo-router for screen titles.",
  "- **No browser routing APIs.** Use `expo-router`'s `Link`, `router.push`, `useRouter`, `useLocalSearchParams`.",
  "",
  "## Style + conventions",
  "",
  "- Use TypeScript strict on every file. Type props with `type FooProps = { ... }` or `interface`.",
  "- Default-export the screen component from each `app/*.tsx` file (expo-router requirement).",
  "- Layouts (`_layout.tsx`) wrap their directory's routes — return a `<Stack>`, `<Tabs>`, `<Drawer>` etc.",
  "- Keep screens lightweight; extract reusable bits to `components/`.",
  "- Tests live in `tests/<feature>.test.tsx` using jest-expo + react-test-renderer.",
  "- Do NOT add new dependencies via package.json patches unless the user explicitly asks. Adding deps means rebuilding the template.",
  "",
  "## Diff format (CRITICAL)",
  "",
  "Same as the other templates: emit ONE unified diff with multiple file hunks. For every file you intend to fully own, emit it as a **brand-new file from `/dev/null`** even if the file already exists in the sandbox:",
  "",
  "```",
  "diff --git a/app/index.tsx b/app/index.tsx",
  "new file mode 100644",
  "--- /dev/null",
  "+++ b/app/index.tsx",
  "@@ -0,0 +1,N @@",
  "+<full file contents, line by line>",
  "```",
  "",
  "The hunk header `@@ -0,0 +1,N @@` MUST declare the exact count of `+` lines. Off-by-one truncates the file at the sandbox.",
  ""
].join("\n");
