/**
 * Per-template prompt fragment for atlas-graphql-yoga (Bun 1.2+ + GraphQL
 * Yoga 5.x + Pothos 4.x code-first SchemaBuilder + Drizzle ORM + Zod).
 * Plan T.2.2.
 */
export const GRAPHQL_YOGA_PROMPT = [
  "## Target sandbox",
  "",
  "Your diff will be applied to a live Bun 1.2+ + GraphQL Yoga 5.x + Pothos 4.x project running in an E2B sandbox (template: atlas-graphql-yoga).",
  "",
  "- The dev-server entry is **`src/server.ts`** — `Bun.serve({ fetch })` mounts Yoga at `/graphql` and ships a smoke `/health` JSON endpoint and a `/` metadata route. Hot-reload is on (`bun run --hot`).",
  "- The schema is **code-first via Pothos** in `src/schema/`. Add new fields to `src/schema/index.ts` (or organize into `src/schema/<feature>.ts` files imported from `index.ts`). Always export the final schema as `export const schema = builder.toSchema();` from `src/schema/index.ts`.",
  "- The Pothos `SchemaBuilder` lives in `src/schema/builder.ts` — extend the `AtlasPothosTypes` interface there to add Context fields, Drizzle types, etc. Import `builder` from `./builder.js` in every schema file.",
  "- Add tests in `tests/<feature>.test.ts` using `bun:test` (`describe`, `it`, `expect`). Boot the server with `createServer({ port: 0 })` and `fetch` the URL.",
  "",
  "## What's installed (use these — don't reinvent)",
  "",
  "- **graphql 16.x** — `import { GraphQLError } from \"graphql\";`",
  "- **graphql-yoga 5.x** — already wired in `server.ts` via `createYoga({ schema, graphqlEndpoint: \"/graphql\" })`. GraphiQL is on at GET `/graphql`.",
  "- **@pothos/core 4.x** — `import SchemaBuilder from \"@pothos/core\";` (already in `builder.ts`)",
  "- **@pothos/plugin-drizzle** — for ORM-backed resolvers; imported on demand when the dev wires a real DB",
  "- **drizzle-orm 0.36+** — `import { drizzle } from \"drizzle-orm/postgres-js\";` (or the SQLite/MySQL driver — pick the one that matches what you're connecting to)",
  "- **zod 3.x** — `import { z } from \"zod\";` for input validation; use in resolvers as `z.object({...}).parse(args.input)`",
  "- **bun:test** — `import { describe, it, expect, beforeAll, afterAll } from \"bun:test\";`",
  "- **bun:sqlite** — built into Bun for in-process SQLite when you don't want a Postgres connection",
  "",
  "## Pothos code-first idioms (CRITICAL)",
  "",
  "- Define types via `builder.objectType(...)`, `builder.inputType(...)`, `builder.enumType(...)`. Pothos infers the GraphQL type from the TS type — use `class` declarations as the carrier or interface stubs.",
  "- Define the root `Query` once with `builder.queryType({ fields: (t) => ({...}) })`. Add to it via `builder.queryFields((t) => ({...}))` from feature files.",
  "- Same for `builder.mutationType` / `builder.mutationFields`. Same for `builder.subscriptionType`.",
  "- Resolver signature: `resolve: (root, args, ctx, info) => value | Promise<value>`. Args are typed from the `args` field of the field definition; ctx is `AtlasPothosTypes['Context']`.",
  "- Always set `t.string({ description: \"...\" })` (or whatever scalar) — descriptions ship to GraphiQL and to schema introspection.",
  "- Use `t.relation(...)` / `t.field({ type: SomeRef })` for object refs; the Drizzle plugin auto-resolves these with N+1 batching when wired up.",
  "- Throw `new GraphQLError(\"...\", { extensions: { code: \"...\" } })` for typed errors — Yoga formats them per the GraphQL spec.",
  "- Inputs go through `builder.inputType(...)`. Validate with Zod at the resolver boundary, not via Pothos validation plugins — keeps the validator co-located with the resolver.",
  "",
  "## Yoga + Bun.serve idioms",
  "",
  "- The Yoga handler is fetch-style: `yoga.fetch(request) -> Response`. Bun.serve passes `request` directly to it.",
  "- Do NOT add Express, Fastify, Hono, or any other server. Bun.serve IS the server. Yoga IS the GraphQL handler.",
  "- Keep `/health` and `/` ahead of the Yoga handler in the `fetch` switch — they're plain JSON, no GraphQL involved.",
  "- For subscriptions, Yoga handles SSE/WebSocket transport automatically when `subscriptionType` is defined — no extra plumbing.",
  "",
  "## Style + conventions",
  "",
  "- TypeScript strict mode. No `any` (use `unknown` + type narrowing).",
  "- Use ESM imports with `.js` extensions (Bun + tsc-bundler resolves the `.ts` source).",
  "- Async resolvers default; sync only for trivial computed fields.",
  "- Do NOT add new npm dependencies via package.json patches unless the user explicitly asks. Adding deps means rebuilding the template.",
  "",
  "## Diff format (CRITICAL)",
  "",
  "Same as the other templates: emit ONE unified diff with multiple file hunks. For every file you intend to fully own, emit it as a **brand-new file from `/dev/null`** even if the file already exists in the sandbox:",
  "",
  "```",
  "diff --git a/src/schema/users.ts b/src/schema/users.ts",
  "new file mode 100644",
  "--- /dev/null",
  "+++ b/src/schema/users.ts",
  "@@ -0,0 +1,N @@",
  "+<full file contents, line by line>",
  "```",
  "",
  "The hunk header `@@ -0,0 +1,N @@` MUST declare the exact count of `+` lines. Off-by-one truncates the file at the sandbox.",
  ""
].join("\n");
