/**
 * Per-template prompt fragment for atlas-hono-bun (Bun 1.2+ runtime +
 * Hono 4.x + Drizzle ORM 0.36+ + Zod 3 + postgres-js). Plan T.2.1.
 */
export const HONO_BUN_PROMPT = [
  "## Target sandbox",
  "",
  "Your diff will be applied to a live Bun 1.2+ + Hono 4.x project running in an E2B sandbox (template: atlas-hono-bun). Bun is BOTH the runtime AND the package manager AND the test runner — there is no `node`, no `npm`, no `tsx`, no `vitest` in this image.",
  "",
  "- The dev-server entry is **`src/index.ts`** — `Bun.serve({ port, fetch: app.fetch })`. URL `/` returns app metadata; `/health` returns liveness.",
  "- Add new feature routers under `src/routes/<feature>.ts` exporting a `Hono` instance, then mount in `src/index.ts` via `app.route(\"/<prefix>\", featureRouter)`.",
  "- Add Drizzle schemas in `src/db/schema.ts` (or per-feature `src/db/<feature>.ts`) using `pgTable(...)`. After schema changes, run `bun run drizzle:generate` to emit migration SQL.",
  "- Add tests in `tests/<feature>.test.ts` using `bun:test` (`import { describe, it, expect } from \"bun:test\"`).",
  "- Use `app.request(\"/path\")` from inside tests to exercise routes — Hono's default export IS a `fetch` handler, no real server needed.",
  "",
  "## What's installed (use these — don't reinvent)",
  "",
  "- **hono 4.6+** — `import { Hono } from \"hono\";`",
  "- **@hono/zod-validator** — `import { zValidator } from \"@hono/zod-validator\";` for typed request bodies / queries / params",
  "- **zod 3.23+** — `import { z } from \"zod\";`",
  "- **drizzle-orm 0.36+** — `import { pgTable, text, integer, ... } from \"drizzle-orm/pg-core\";` and `import { drizzle } from \"drizzle-orm/postgres-js\";`",
  "- **postgres 3.4+** (the postgres-js driver) — `import postgres from \"postgres\";`",
  "- **drizzle-kit** (dev) — CLI only; do not import",
  "- **bun:test** — built-in, no install needed",
  "- **TypeScript 5.6 strict** — `noUncheckedIndexedAccess`, `verbatimModuleSyntax: false`, `moduleResolution: bundler`",
  "",
  "## Bun-specific APIs (prefer these over Node equivalents)",
  "",
  "- `Bun.env.<NAME>` — environment variables (faster than `process.env` in Bun; both work).",
  "- `Bun.serve({ port, fetch })` — HTTP server. Already wired in `src/index.ts`; you generally don't need a second one.",
  "- `Bun.file(\"path\")` — file reads as a `BunFile` (subclass of `Blob`). Use for static asset serving.",
  "- `Bun.password.hash(...) / Bun.password.verify(...)` — argon2 passwords, no extra dep.",
  "- Do NOT install `dotenv` — Bun auto-loads `.env` files.",
  "- Do NOT install `tsx` / `ts-node` — Bun runs `.ts` natively.",
  "- Do NOT install `nodemon` — `bun --hot run src/index.ts` covers hot reload.",
  "",
  "## Hono idioms",
  "",
  "- Return JSON via `c.json(payload, statusCode?)`. Hono auto-serializes.",
  "- Throw HTTP errors via `import { HTTPException } from \"hono/http-exception\"; throw new HTTPException(404, { message: \"...\" });`",
  "- Mount middleware via `app.use(\"*\", middlewareFn)` (use `\"*\"` for global, path for scoped).",
  "- Validate request bodies with `zValidator(\"json\", SchemaZ)` then read via `c.req.valid(\"json\")` — fully typed.",
  "- For URL params: `app.get(\"/items/:id\", c => c.json({ id: c.req.param(\"id\") }))`.",
  "",
  "## Drizzle idioms",
  "",
  "- Define tables in `src/db/schema.ts`: `export const users = pgTable(\"users\", { id: uuid(...).primaryKey().defaultRandom(), ... });`",
  "- Get inferred types: `import type { InferSelectModel, InferInsertModel } from \"drizzle-orm\"; type User = InferSelectModel<typeof users>;`",
  "- Query: `const rows = await db.select().from(users).where(eq(users.id, someId));` (await, NOT a promise chain).",
  "- Insert: `await db.insert(users).values({ ... }).returning();`",
  "- Connection: `import postgres from \"postgres\"; import { drizzle } from \"drizzle-orm/postgres-js\"; const client = postgres(Bun.env.DATABASE_URL!); const db = drizzle(client);`",
  "- Do NOT add `prisma` — Drizzle is the chosen ORM; mixing them confuses migrations.",
  "",
  "## Style + conventions",
  "",
  "- Use `import` paths WITH `.ts` extension (e.g., `import x from \"./routes/example.ts\"`). Bun + the bundler resolution mode in tsconfig require explicit extensions for relative imports.",
  "- Use `type` imports for type-only references: `import type { Context } from \"hono\";`",
  "- Use `const` for everything that isn't reassigned.",
  "- Async route handlers: `async (c) => { ... }`. Never block with sync I/O.",
  "- Do NOT add new deps via package.json patches unless the user explicitly asks — adding deps means rebuilding the template.",
  "",
  "## Diff format (CRITICAL)",
  "",
  "Same as the Next.js + FastAPI templates: emit ONE unified diff with multiple file hunks. For every file you intend to fully own, emit it as a **brand-new file from `/dev/null`** even if the file already exists in the sandbox:",
  "",
  "```",
  "diff --git a/src/routes/users.ts b/src/routes/users.ts",
  "new file mode 100644",
  "--- /dev/null",
  "+++ b/src/routes/users.ts",
  "@@ -0,0 +1,N @@",
  "+<full file contents, line by line>",
  "```",
  "",
  "The hunk header `@@ -0,0 +1,N @@` MUST declare the exact count of `+` lines.",
  ""
].join("\n");
