/**
 * Per-template prompt fragment for atlas-fastapi (Python 3.12 + FastAPI +
 * Pydantic 2 + uvicorn + sqlalchemy + alembic). Plan T.1.
 */
export const FASTAPI_PROMPT = [
  "## Target sandbox",
  "",
  "Your diff will be applied to a live Python 3.12 + FastAPI 0.115+ project running in an E2B sandbox (template: atlas-fastapi).",
  "",
  "- The dev-server entry is **`app/main.py`** — `app = FastAPI(...)`. URL `/` returns app metadata; `/health` returns liveness; `/docs` is Swagger UI auto-generated from your route signatures.",
  "- Add new routes to `app/main.py` (single-file is fine for small APIs) OR organize into `app/routers/<feature>.py` and `app.include_router(...)` from main.",
  "- Add Pydantic models in `app/models/<feature>.py` for request/response shapes.",
  "- Add SQLAlchemy models in `app/db/<feature>.py`.",
  "- Add Alembic migrations in `alembic/versions/` if you change DB schema.",
  "- Add tests in `tests/test_<feature>.py` using `fastapi.testclient.TestClient`.",
  "",
  "## What's installed (use these — don't reinvent)",
  "",
  "- **fastapi 0.115+** — `from fastapi import FastAPI, HTTPException, Depends`",
  "- **pydantic 2.x** — `from pydantic import BaseModel, Field`",
  "- **uvicorn** — already running the app via `uv run uvicorn app.main:app`",
  "- **httpx** — async HTTP client (use for outbound calls)",
  "- **sqlalchemy 2.x** — `from sqlalchemy import select, Column, ...`",
  "- **alembic** — migrations CLI; `uv run alembic ...`",
  "- **psycopg2-binary** — Postgres driver (sync); use `asyncpg` only if you add it",
  "- **pytest + pytest-asyncio** — test framework with `asyncio_mode = auto`",
  "- **ruff** — lint + format; pre-configured for line-length 100, py312",
  "",
  "## Style + conventions",
  "",
  "- Use type hints on every function signature (PEP 695 syntax fine).",
  "- Use Pydantic v2 idioms: `model_config = ConfigDict(...)`, `field_validator`, `model_dump()` (not `.dict()`).",
  "- Async route handlers default; use sync only for CPU-bound work.",
  "- Return JSON-serializable Pydantic models from routes (FastAPI auto-serializes).",
  "- Raise `HTTPException(status_code=..., detail=...)` for HTTP errors.",
  "- Use `Depends(...)` for DB session, auth, settings injection.",
  "- Do NOT add new pip dependencies via pyproject.toml patches unless the user explicitly asks. Adding deps means rebuilding the template.",
  "",
  "## Diff format (CRITICAL)",
  "",
  "Emit ONE unified diff with multiple file hunks. For every file you intend to fully own, emit it as a **brand-new file from `/dev/null`**:",
  "",
  "```",
  "diff --git a/app/routers/users.py b/app/routers/users.py",
  "new file mode 100644",
  "--- /dev/null",
  "+++ b/app/routers/users.py",
  "@@ -0,0 +1,N @@",
  "+<full file contents>",
  "```",
  "",
  "The hunk header `@@ -0,0 +1,N @@` MUST declare the exact count of `+` lines.",
  ""
].join("\n");
