"""Canonical invariant codes emitted by the TS validator.

These mirror packages/spec-graph-schema/src/invariants/*.ts exactly.
The TS build emits invariant-codes.json (bundled inside this package's
schema/ directory); test_invariant_codes.py asserts this enum stays in
lockstep with that artifact.

Python consumers do NOT run invariant logic — these codes exist so that
cross-language tooling (error-reporting UIs, cloud_migration future
fusion) can speak the same error vocabulary as the TS validator.
"""
from __future__ import annotations

from enum import Enum


class InvariantCode(str, Enum):
    I01_PAGE_MISSING_ROUTEREF = "I01_PAGE_MISSING_ROUTEREF"
    I02_ENDPOINT_MISSING_ROUTEREF = "I02_ENDPOINT_MISSING_ROUTEREF"
    I03_AUTH_PAGE_MISSING_BOUNDARY = "I03_AUTH_PAGE_MISSING_BOUNDARY"
    I04_PII_ENDPOINT_MISSING_AUTH = "I04_PII_ENDPOINT_MISSING_AUTH"
    I04_PII_ENDPOINT_MISSING_COMPLIANCE = "I04_PII_ENDPOINT_MISSING_COMPLIANCE"
    I05_PII_MODEL_MISSING_RLS = "I05_PII_MODEL_MISSING_RLS"
    I06_DEPENDENCY_HAS_CRITICAL_CVE = "I06_DEPENDENCY_HAS_CRITICAL_CVE"
    I07_RENDERS_DANGLING_REF = "I07_RENDERS_DANGLING_REF"
    I07_RENDERS_WRONG_KIND = "I07_RENDERS_WRONG_KIND"
    I08_BASELINE_COMPLIANCE_MISSING = "I08_BASELINE_COMPLIANCE_MISSING"
    I08_BASELINE_COMPLIANCE_DUPLICATED = "I08_BASELINE_COMPLIANCE_DUPLICATED"
    I09_MISSING_TEST_COVERAGE = "I09_MISSING_TEST_COVERAGE"
    I10_AIFEATURE_PERSONALIZED_MISSING_COMPLIANCE = "I10_AIFEATURE_PERSONALIZED_MISSING_COMPLIANCE"
    I11_GENERATED_MEDIA_MISSING_PROVIDER = "I11_GENERATED_MEDIA_MISSING_PROVIDER"
    I12_PII_CLIENTSTATE_MISSING_COMPLIANCE = "I12_PII_CLIENTSTATE_MISSING_COMPLIANCE"
    I13_PROTECTED_TARGET_MISSING_BASELINE_TEST = "I13_PROTECTED_TARGET_MISSING_BASELINE_TEST"
    I14_MEDIAASSET_KIND_PHASE_B = "I14_MEDIAASSET_KIND_PHASE_B"
    I15_WORKLOAD_TOPOLOGY_REFERENCES_INVALID = "I15_WORKLOAD_TOPOLOGY_REFERENCES_INVALID"
    I16_PII_MODEL_MISSING_STORES_DATA_IN = "I16_PII_MODEL_MISSING_STORES_DATA_IN"


INVARIANT_CODES: list[str] = sorted(code.value for code in InvariantCode)
