# AUTO-GENERATED from spec-graph.v1.schema.json — DO NOT EDIT
# Source: packages/spec-graph-schema/src/
# Regenerate: pnpm py:gen
# Schema hash: sha256:f85340bb44273cc5c0f9f4e11c02faa873e927160f29a934e309b0800bfc6a97
# generated by datamodel-codegen:
#   filename:  spec-graph.v1.schema.json

from __future__ import annotations

from datetime import datetime
from enum import Enum
from typing import Any, Literal
from uuid import UUID

from pydantic import (
    BaseModel,
    ConfigDict,
    Field,
    PositiveInt,
    RootModel,
    confloat,
    constr,
)


class SchemaVersion(Enum):
    FIELD_1_0_0 = '1.0.0'
    FIELD_1_1_0 = '1.1.0'


class ComplianceClassName(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Tier(Enum):
    ATLAS_RUN = 'atlas-run'
    BYO_CLOUD = 'byo-cloud'
    SELF_HOSTED = 'self-hosted'


class DatabaseProvider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    tier: Tier
    provider: constr(min_length=1)
    region: constr(min_length=1)
    connection_string_ref: constr(min_length=1) = Field(
        ..., alias='connectionStringRef'
    )


class RenderMode(Enum):
    SSR = 'ssr'
    SSG = 'ssg'
    CSR = 'csr'
    ISR = 'isr'


class Page(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['page']
    id: constr(
        pattern=r'^(page|route|component|clientstate|model|endpoint|flow|authboundary|test|designtoken|dependency|compliance|aifeature|mediaasset|region|dataresidency|runtime|provider|workloadtopology):[A-Za-z0-9._-]+$'
    )
    extensions: dict[str, Any] | None = {}
    path: constr(min_length=1)
    title: constr(min_length=1)
    layout: str | None = None
    render_mode: RenderMode = Field(..., alias='renderMode')
    metadata: dict[str, Any] | None = None
    auth_required: bool | None = Field(False, alias='authRequired')
    route_ref: str | None = Field(None, alias='routeRef')
    a11y_annotations: dict[str, str] | None = Field(None, alias='a11yAnnotations')


class Method(Enum):
    GET = 'GET'
    HEAD = 'HEAD'
    POST = 'POST'
    PUT = 'PUT'
    PATCH = 'PATCH'
    DELETE = 'DELETE'
    OPTIONS = 'OPTIONS'


class HandlerType(Enum):
    PAGE = 'page'
    ENDPOINT = 'endpoint'
    MIDDLEWARE = 'middleware'


class StyleApproach(Enum):
    TAILWIND = 'tailwind'
    CSS_MODULES = 'css-modules'
    VANILLA_EXTRACT = 'vanilla-extract'
    STYLED_COMPONENTS = 'styled-components'
    EMOTION = 'emotion'
    INLINE = 'inline'


class StateKind(Enum):
    CONTEXT = 'context'
    ZUSTAND_STORE = 'zustand-store'
    REDUCER = 'reducer'
    QUERY_CACHE = 'query-cache'
    FORM_STATE = 'form-state'
    ROUTE_STATE = 'route-state'


class Persistence(Enum):
    NONE = 'none'
    SESSION_STORAGE = 'sessionStorage'
    LOCAL_STORAGE = 'localStorage'
    URL = 'url'


class Scope(Enum):
    PAGE = 'page'
    LAYOUT = 'layout'
    APP = 'app'
    FLOW = 'flow'


class PiiClassification(Enum):
    NONE = 'none'
    INDIRECT = 'indirect'
    DIRECT = 'direct'
    SENSITIVE = 'sensitive'


class Kind(Enum):
    ONE_TO_ONE = 'one-to-one'
    ONE_TO_MANY = 'one-to-many'
    MANY_TO_ONE = 'many-to-one'
    MANY_TO_MANY = 'many-to-many'


class Relation(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    name: constr(min_length=1)
    to: constr(min_length=1)
    kind: Kind


class OnItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Index(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    on: list[OnItem] = Field(..., min_length=1)
    unique: bool | None = False


class RlsPolicies(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    select: str | None = None
    insert: str | None = None
    update: str | None = None
    delete: str | None = None


class RateLimit(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    window: constr(pattern=r'^[1-9][0-9]*(ms|s|m|h|d)$')
    max: PositiveInt


class Step(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    label: constr(min_length=1)
    surface: str | None = None


class EntryPoint(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Type(Enum):
    PUBLIC = 'public'
    AUTHENTICATED = 'authenticated'
    ROLE = 'role'
    PERMISSION = 'permission'


class Layer(Enum):
    L1 = 'L1'
    L2 = 'L2'
    L3 = 'L3'
    L4 = 'L4'
    L5 = 'L5'


class Source(Enum):
    GENERATED = 'generated'
    USER = 'user'
    BASELINE = 'baseline'


class CoversRefItem(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Category(Enum):
    COLOR = 'color'
    SPACING = 'spacing'
    TYPOGRAPHY = 'typography'
    RADIUS = 'radius'
    SHADOW = 'shadow'
    MOTION = 'motion'


class Scale(Enum):
    LIGHT = 'light'
    DARK = 'dark'


class Severity(Enum):
    NONE = 'none'
    LOW = 'low'
    MEDIUM = 'medium'
    HIGH = 'high'
    CRITICAL = 'critical'


class Finding(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    id: constr(min_length=1)
    cvss: confloat(ge=0.0, le=10.0) | None = None


class CveScanStatus(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    scanned_at: datetime = Field(..., alias='scannedAt')
    severity: Severity
    findings: list[Finding] | None = []


class Name(Enum):
    BASELINE = 'baseline'
    GDPR = 'GDPR'
    HIPAA = 'HIPAA'
    SOC2_LITE = 'SOC2-lite'
    PCI_DSS = 'PCI-DSS'
    DPDP_INDIA = 'DPDP-India'
    LGPD = 'LGPD'


class Scope1(Enum):
    GLOBAL_ = 'global'
    MODEL = 'model'
    ENDPOINT = 'endpoint'
    FEATURE = 'feature'


class Attestation(Enum):
    SELF_ATTESTED = 'self-attested'
    THIRD_PARTY_AUDITED = 'third-party-audited'
    CERTIFIED = 'certified'


class Category1(Enum):
    SUMMARIZATION = 'summarization'
    EXTRACTION = 'extraction'
    CLASSIFICATION = 'classification'
    GENERATION = 'generation'
    TRANSLATION = 'translation'
    QA = 'qa'
    SEARCH = 'search'
    TRANSFORMATION = 'transformation'
    AGENT = 'agent'
    OTHER = 'other'


class InputModality(Enum):
    TEXT = 'text'
    IMAGE = 'image'
    AUDIO = 'audio'
    VIDEO = 'video'
    MULTIMODAL = 'multimodal'


class Grounding(Enum):
    NONE = 'none'
    RAG = 'rag'
    TOOL_USE = 'tool-use'
    STRUCTURED_CONTEXT = 'structured-context'


class Personalization(Enum):
    NONE = 'none'
    SESSION = 'session'
    ACCOUNT = 'account'
    CROSS_ACCOUNT = 'cross-account'


class PrivacyMode(Enum):
    NO_RETAIN = 'no-retain'
    RETAIN_7D = 'retain-7d'
    RETAIN_30D = 'retain-30d'
    RETAIN_INDEFINITE = 'retain-indefinite'


class SafetyContract(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    prompt_injection_guard: bool = Field(..., alias='promptInjectionGuard')
    hallucination_guard: bool = Field(..., alias='hallucinationGuard')
    pii_redaction: bool | None = Field(None, alias='piiRedaction')
    content_filter: bool | None = Field(None, alias='contentFilter')


class CostTier(Enum):
    FAST = 'fast'
    STANDARD = 'standard'
    PREMIUM = 'premium'


class MediaKind(Enum):
    IMAGE = 'image'
    ICON = 'icon'
    ILLUSTRATION = 'illustration'


class LicenseStatus(Enum):
    GENERATED = 'generated'
    USER_UPLOADED = 'user-uploaded'
    LICENSED_THIRD_PARTY = 'licensed-third-party'
    PUBLIC_DOMAIN = 'public-domain'


class Language(Enum):
    NODE = 'node'
    PYTHON = 'python'
    GO = 'go'
    RUST = 'rust'
    JAVA = 'java'
    RUBY = 'ruby'
    OTHER = 'other'


class Type1(Enum):
    HYPERSCALER = 'hyperscaler'
    REGIONAL = 'regional'
    ON_PREM = 'on-prem'
    SOVEREIGN = 'sovereign'


class Shape(Enum):
    SINGLE_REGION = 'single-region'
    MULTI_REGION_ACTIVE_PASSIVE = 'multi-region-active-passive'
    MULTI_REGION_ACTIVE_ACTIVE = 'multi-region-active-active'
    EDGE_ONLY = 'edge-only'
    HYBRID_ON_PREM_CLOUD = 'hybrid-on-prem-cloud'


class Extensions(RootModel[dict[str, Any] | None]):
    root: dict[str, Any] | None = None


class Id(
    RootModel[
        constr(
            pattern=r'^(page|route|component|clientstate|model|endpoint|flow|authboundary|test|designtoken|dependency|compliance|aifeature|mediaasset|region|dataresidency|runtime|provider|workloadtopology):[A-Za-z0-9._-]+$'
        )
    ]
):
    root: constr(
        pattern=r'^(page|route|component|clientstate|model|endpoint|flow|authboundary|test|designtoken|dependency|compliance|aifeature|mediaasset|region|dataresidency|runtime|provider|workloadtopology):[A-Za-z0-9._-]+$'
    )


class Route(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['route']
    id: Id
    extensions: Extensions | None = None
    pattern: constr(min_length=1)
    method: Method
    handler_type: HandlerType = Field(..., alias='handlerType')


class Component(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['component']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    props_schema: dict[str, Any] | None = Field(None, alias='propsSchema')
    is_server_component: bool | None = Field(False, alias='isServerComponent')
    style_approach: StyleApproach = Field(..., alias='styleApproach')
    a11y_annotations: dict[str, str] | None = Field(None, alias='a11yAnnotations')


class ClientState(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['clientstate']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    state_kind: StateKind = Field(..., alias='stateKind')
    schema_: dict[str, Any] | None = Field(None, alias='schema')
    persistence: Persistence
    scope: Scope
    pii_classification: PiiClassification | None = Field(
        'none', alias='piiClassification'
    )


class Model(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['model']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    fields: dict[str, Any]
    relations: list[Relation] | None = []
    indexes: list[Index] | None = []
    rls_policies: RlsPolicies | None = Field({}, alias='rlsPolicies')
    pii_classification: PiiClassification | None = Field(
        'none', alias='piiClassification'
    )
    data_retention_days: PositiveInt | None = Field(None, alias='dataRetentionDays')


class Endpoint(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['endpoint']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    route_ref: constr(min_length=1) = Field(..., alias='routeRef')
    method: Method
    input_schema: dict[str, Any] | None = Field(None, alias='inputSchema')
    output_schema: dict[str, Any] | None = Field(None, alias='outputSchema')
    auth_ref: str | None = Field(None, alias='authRef')
    rate_limit: RateLimit | None = Field(None, alias='rateLimit')


class Flow(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['flow']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    steps: list[Step] = Field(..., min_length=1)
    entry_points: list[EntryPoint] = Field(..., alias='entryPoints', min_length=1)
    success_criteria: str | None = Field(None, alias='successCriteria')
    failure_paths: list[constr(min_length=1)] | None = Field([], alias='failurePaths')


class AuthBoundary(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['authboundary']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    type: Type
    roles: list[constr(min_length=1)] | None = []
    permissions: list[constr(min_length=1)] | None = []
    bypass_conditions: list[constr(min_length=1)] | None = Field(
        [], alias='bypassConditions'
    )


class Test(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['test']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    layer: Layer
    source: Source
    filepath: constr(min_length=1)
    covers_ref: list[CoversRefItem] = Field(..., alias='coversRef', min_length=1)


class DesignToken(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['designtoken']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    category: Category
    value: str | float | dict[str, Any]
    scale: Scale | None = None
    contrast_group: str | None = Field(None, alias='contrastGroup')


class Dependency(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['dependency']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    version: constr(pattern=r'^\d+\.\d+\.\d+(?:-[0-9A-Za-z-.]+)?$')
    purpose: str | None = None
    license: constr(min_length=1)
    cve_scan_status: CveScanStatus = Field(..., alias='cveScanStatus')


class ComplianceClass(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['compliance']
    id: Id
    extensions: Extensions | None = None
    name: Name
    scope: Scope1
    attestation: Attestation
    effective_date: constr(pattern=r'^\d{4}-\d{2}-\d{2}$') = Field(
        ..., alias='effectiveDate'
    )


class AIFeature(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['aifeature']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    category: Category1
    capability_contract: dict[str, Any] = Field(..., alias='capabilityContract')
    input_modality: InputModality = Field(..., alias='inputModality')
    output_modality: InputModality = Field(..., alias='outputModality')
    grounding: Grounding
    personalization: Personalization
    privacy_mode: PrivacyMode = Field(..., alias='privacyMode')
    safety_contract: SafetyContract = Field(..., alias='safetyContract')
    fallback_behavior: constr(min_length=1) = Field(..., alias='fallbackBehavior')
    cost_tier: CostTier = Field(..., alias='costTier')


class MediaAsset(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['mediaasset']
    id: Id
    extensions: Extensions | None = None
    media_kind: MediaKind = Field(..., alias='mediaKind')
    provider_capability: str | None = Field(None, alias='providerCapability')
    generation_prompt: str | None = Field(None, alias='generationPrompt')
    path_or_url: constr(min_length=1) = Field(..., alias='pathOrUrl')
    alt_text: constr(min_length=1) = Field(..., alias='altText')
    license_status: LicenseStatus = Field(..., alias='licenseStatus')
    content_hash: constr(pattern=r'^sha256:[0-9a-f]{6,64}$') = Field(
        ..., alias='contentHash'
    )
    personalization_context: str | None = Field('none', alias='personalizationContext')


class Region(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['region']
    id: Id
    extensions: Extensions | None = None
    code: constr(min_length=1)
    cloud_provider_ref: str | None = Field(None, alias='cloudProviderRef')
    jurisdiction_ref: str | None = Field(None, alias='jurisdictionRef')


class DataResidency(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['dataresidency']
    id: Id
    extensions: Extensions | None = None
    jurisdiction: constr(min_length=1)
    notes: str | None = None


class Runtime(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['runtime']
    id: Id
    extensions: Extensions | None = None
    language: Language
    version: constr(min_length=1)


class Provider(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['provider']
    id: Id
    extensions: Extensions | None = None
    name: constr(min_length=1)
    type: Type1
    region_refs: list[str] | None = Field([], alias='regionRefs')


class WorkloadTopology(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    kind: Literal['workloadtopology']
    id: Id
    extensions: Extensions | None = None
    shape: Shape
    provider_refs: list[str] = Field(..., alias='providerRefs', min_length=1)
    region_refs: list[str] = Field(..., alias='regionRefs', min_length=1)


class RendersEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['renders']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class FetchesEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['fetches']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class ReadsEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['reads']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class MutatesEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['mutates']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class RequiresEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['requires']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class CoversEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['covers']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class DependsOnEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['dependsOn']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class StyledByEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['styledBy']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class SubjectToEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['subjectTo']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class SupersedesEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['supersedes']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class PowersEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['powers']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class DisplaysEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['displays']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class ManagesEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['manages']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class RunsOnEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['runsOn']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class StoresDataInEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['storesDataIn']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class MigratesToEdge(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    type: Literal['migratesTo']
    from_: Id = Field(..., alias='from')
    to: Id
    extensions: Extensions | None = None


class SpecGraph(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    schema_version: SchemaVersion = Field(..., alias='schemaVersion')
    project_id: UUID = Field(..., alias='projectId')
    name: constr(min_length=1)
    compliance_classes: list[ComplianceClassName] = Field(
        ..., alias='complianceClasses', min_length=1
    )
    database_provider: DatabaseProvider = Field(..., alias='databaseProvider')
    template_digest: constr(pattern=r'^sha256:[0-9a-f]{6,64}$') = Field(
        ..., alias='templateDigest'
    )
    created_at: datetime = Field(..., alias='createdAt')
    updated_at: datetime = Field(..., alias='updatedAt')
    nodes: dict[
        str,
        Page
        | Route
        | Component
        | ClientState
        | Model
        | Endpoint
        | Flow
        | AuthBoundary
        | Test
        | DesignToken
        | Dependency
        | ComplianceClass
        | AIFeature
        | MediaAsset
        | Region
        | DataResidency
        | Runtime
        | Provider
        | WorkloadTopology,
    ]
    edges: list[
        RendersEdge
        | FetchesEdge
        | ReadsEdge
        | MutatesEdge
        | RequiresEdge
        | CoversEdge
        | DependsOnEdge
        | StyledByEdge
        | SubjectToEdge
        | SupersedesEdge
        | PowersEdge
        | DisplaysEdge
        | ManagesEdge
        | RunsOnEdge
        | StoresDataInEdge
        | MigratesToEdge
    ]
    extensions: Extensions | None = None


class SpecGraphRoot(RootModel[SpecGraph]):
    root: SpecGraph
